# Generated by Django 4.2.18 on 2025-01-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=55)),
                ('phone_number', models.CharField(max_length=18)),
                ('email', models.CharField(max_length=125, unique=True)),
                ('password', models.CharField(max_length=125)),
                ('role_id', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'custom_user',
            },
        ),
    ]
