# Generated by Django 4.2.18 on 2025-02-11 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userrole', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='workscheduleday',
            name='work_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_of_week', to='accounts.workschedule', verbose_name='Офис'),
        ),
    ]
