# Generated by Django 4.2.18 on 2025-02-11 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='days_of_week',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='start_time',
        ),
        migrations.AlterModelTable(
            name='workschedule',
            table='work_schedule',
        ),
        migrations.CreateModel(
            name='WorkScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Понедельник-Пятница', 'Понедельник-Пятница'), ('Суббота-Воскресенье', 'Суббота-Воскресенье')], max_length=50, verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_of_week', to='accounts.workschedule')),
            ],
            options={
                'verbose_name': 'День и время работы',
                'verbose_name_plural': 'Дни и время работы',
                'db_table': 'work_schedule_day',
            },
        ),
    ]
