# Generated by Django 4.2.18 on 2025-02-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='service_office',
        ),
    ]
