# Generated by Django 4.2.18 on 2025-01-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='role_id',
            field=models.IntegerField(default=1),
        ),
    ]
