# Generated by Django 4.2.18 on 2025-02-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusers',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='customusers',
            name='full_name',
            field=models.CharField(max_length=55, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='password',
            field=models.CharField(max_length=125, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='phone_number',
            field=models.CharField(max_length=18, verbose_name='Номер телефона'),
        ),
    ]
