# Generated by Django 4.2.18 on 2025-01-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customusers_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
