# Generated by Django 4.2.18 on 2025-02-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_workschedule_days_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workscheduleday',
            name='is_off_day',
            field=models.BooleanField(default=False, verbose_name='Выходной день'),
        ),
        migrations.AlterField(
            model_name='workscheduleday',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='workscheduleday',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
    ]
