# Generated by Django 4.2.18 on 2025-01-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customusers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='email',
            field=models.CharField(max_length=125, unique=True),
        ),
    ]
